### ISSUE TITLE
Sacred Light Recipe acting odd with Ender IO

### ISSUE THREAD

**Issue by Routhinator** [CorwinJV/MobTotems#14]
Not sure what's going on here, but in 1.10.2 with EnderIO and SpongeForge I'm getting the following as the recipe for the Sacred Light block:

![screenshot from 2016-12-10 17 38 26](https://cloud.githubusercontent.com/assets/727535/21077427/ea447c8a-beff-11e6-98f0-ef965f19e63e.png)

This is quite a bit more expensive than the documented recipe on Curse. I don't see an option in the config or mention of it changing. I'm probably going to override it with a script for now, but thought I should bring this up.

**Comment by CorwinJV** [comment]
Are you using All the Mods by chance? They're using a modified recipe because they thought it was too OP, I believe. xD

**Comment by Routhinator** [comment]
Ahh, I based this pack on all the mods I forgot they have some modifiers.. jeez theres the answer.
