### ISSUE TITLE
Crash after placing incense box

### ISSUE THREAD

**Issue by jasenmoloy** [CorwinJV/MobTotems#20]
Notes
---------
- Was in creative mode and placed the incense box on a Endermen totem.
- [Crash Log](https://github.com/CorwinJV/MobTotems/files/836329/crash-2017-03-11_20.08.33-server.txt)

**Comment by CorwinJV** [comment]
What version / commit?

**Comment by jasenmoloy** [comment]
This is with the current release. I built and ran a local server running `dev` and logged in with the client and the release version of the mod.

**Comment by CorwinJV** [comment]
Can't seem to reproduce this. I put an Ender Totem block down and placed an Incense Kindling Box on top of it / beside it. Tried with a completed 3 part totem.

**Comment by jasenmoloy** [comment]
Here's a copy of the `run` folder. I don't see the minecraft_server.jar file so I'm not sure where ForgeGradle puts it.

[server_run.zip](https://github.com/CorwinJV/MobTotems/files/843514/server_run.zip)

**Comment by CorwinJV** [comment]
Could not reproduce
