### ISSUE TITLE
Animania "Cursed Earth Cows" causing crash

### ISSUE THREAD

**Issue by OrdinatorStouff** [CorwinJV/MobTotems#23]
On official ATM2 server, players have witnessed [Animania bulls in cursed earth farms](https://github.com/AllTheMods/ATM-2/issues/24), as well as Bull Jockies. 

This appears to be a crash involving MobTotems and one such Cursed Earth Cow: https://pastebin.com/YRnBzecz

**Comment by OrdinatorStouff** [comment]
Animania has added a config option to disable Bull Jockeys but if that option is not disabled, this crash can still happen as an interaction between the Cow Totem and the ExU2 cursed earth.

**Comment by CorwinJV** [comment]
Thanks, I'll look into this later if I have time.

**Comment by CorwinJV** [comment]
I think I've addressed this issue by iterating over the loaded tile entities backwards in this event to avoid comodification. 
[View the change](https://github.com/CorwinJV/MobTotems/commit/3870a88b02e170241e01899f69934885f9e55603#diff-f00eb37c8aed02a79e8ca3f67d33b4e9)
