### ISSUE TITLE
1.12 Mob Totem Spawning Issue

### ISSUE THREAD

**Issue by LeChuckXIV** [CorwinJV/MobTotems#24]
Version: 0.3.0

Creeper Totem(with ocelot upgrades) will prevent boss mobs from being spawned, e.g. withers

testing, try to spawn a wither next to the totem

**Comment by CorwinJV** [comment]
The totem is active, correct? 

This isn't really a bug as the creeper totem block prevents aggressive mobs from spawning near it.

**Comment by LeChuckXIV** [comment]
So it's ok to place your soul sand and skulls nearby and have the wither deleted before it spawns, at least as a config option so that you can toggle whether it blocks boss spawning. Or even a whitelist.

**Comment by CorwinJV** [comment]
I see how it's a bummer to lose your materials but it does what it says on the tin. I'll see if I can add something in a future update.
