### ISSUE TITLE
[1.12.2] Config generates empty

### ISSUE THREAD

**Issue by Dragnier** [CorwinJV/MobTotems#25]
Just went looking for the config to change the recipe of the sacred light and found the config file completely empty.

**Comment by CorwinJV** [comment]
When updating to 1.12 I converted the recipes to use the new JSON format. Since the recipes are defined in JSON you can customize them through that system now. 

I've removed that config option and now there aren't any configuration options.

**Comment by Dragnier** [comment]
There is no documentation for the .json recipe format though. A default _example.json with the default recipe would be helpful.

**Comment by CorwinJV** [comment]
The recipe is in the jar file. I can update later with the direct path. The rest of this is really 1.12 stuff and not me specifically. You should be able to make a resource pack which replaces the default recipe with your own. Tbh I think Mojang / forge made this system more complicated than it needs to be. 

I believe that it is possible for me to re-add the cfg option and allow for an easy mode recipe to be added once more but it's quite a bit more complicated to do than it used to be. 

I'll look into it, but for now maybe consider cheating in some nether stars for making sacred light blocks?

**Comment by CorwinJV** [comment]
https://github.com/CorwinJV/MobTotems/blob/master/src/main/resources/assets/mobtotems/recipes/sacred_light.json

**Comment by Dragnier** [comment]
I just tried to use Craft Tweaker to edit the sacred light recipe. It cannot change your recipes at all. Neither remove nor add work; craft tweaker throws errors in the chat on world load when trying. I'm going to guess it's something with your mod causing it not to work since it works with basically any other mod that uses the vanilla crafting method. You might want to look into fixing that.

**Comment by CorwinJV** [comment]
Thanks for the info.

**Comment by CorwinJV** [comment]
Tested mobtotems-1.12.1-0.3.0 with CraftTweaker2-1.12.4.0.9 on Minecraft 1.12.2 and used the following script to add a shapeless crafting recipe of 1 fish to make a sacred light:

val fish = <minecraft:fish>;
recipes.addShapeless("mobtotemsSacredLight", <mobtotems:sacred_light>, [fish]);

No errors here.

**Comment by CorwinJV** [comment]
Just realized that the code feature in github's comments doesn't show all of the characters needed for the script to work. Here's a pastebin with it working:

https://pastebin.com/r13uMZy7

**Comment by Dragnier** [comment]
I finally got this working with a shaped recipe change using craft tweaker on the most current versions available through curse. Not sure what changed, but glad it's working now.
